/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    druidSidebar: [
        { type: "autogenerated", dirName: "1.druid-on-kuberenetes" },
    ],
    pinotSidebar: [{ type: "autogenerated", dirName: "2.pinot-on-kubernetes" }],
    dsoiSidebar: [
        {
            type: "autogenerated",
            dirName: "3.distributed-sytem-operator-interface",
        },
    ],
    operatorSidebar: [{ type: "autogenerated", dirName: "4.operator-runtime" }],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

module.exports = sidebars
